### PR TITLE
Adding 'local' parameter to ks-font-face

### PR DESCRIPTION
**Pull request by EmmanuelBeziat**
In order to improve the font loading, the "local" parameter can be used in a font-face declaration: the declaration will search on the local computer if the typo exists, if not it will charge the webfont at the proper format.

### CODE REVIEW

**Comment by leny** [comment]
Hi, thanks for the PR.

Can you please add some unit tests covering your changes?

**Comment by EmmanuelBeziat** [comment]
Woops, guess I missed the "contributing.md" file. I'll handle this on the afternoon. ;)

**Comment by leny** [comment]
Take all the time you need ;)

**Comment by EmmanuelBeziat** [comment]
Added tests and doc, but still not ok. The test seems to fail because of some linebreaks, I Wonder if it's because I edited the files from Windows. Will try on a mac soon.

**Comment by EmmanuelBeziat** [comment]
Nope, my bad. Was all my fault. All clear now!

**Comment by leny** [comment]
Thanks. I'll try to publish this A.S.A.P.
Don't hesitate to scream if I forgot (got a full load of work right now).

**Comment by leny** [comment]
Merged and published as `0.12.0`. Thanks again.

**Pull request merged**
